### ISSUE TITLE
Nullifier front-running in Miximus

### ISSUE THREAD

**Issue by HarryR** [HarryR/ethsnarks-miximus#2]
An issue may exist with Miximus as it is now, taken from: https://ethresear.ch/t/anonymous-reputation-risking-and-burning/3926/2

@khovratovich comments
> I started reading “How Miximus works” and noticed you use nullifiers to prevent double spending. However if nullifier can be chosen arbitrarily, there is a potential front-run vulnerability: an attacker sees your nullifier before the transaction is mined and tries to slip in with his own leaf and the same nullifier, trying to spend it immediately.
> This attack applies to Zerocoin, but in Zerocash/Zcash it was fixed by requiring the nullifier be deterministic function of the recipient public key. You can do something similar.

@yondonfu comments
> For Miximus, instead of using external_nullifier, perhaps you can define nullifier = H(nullifier_secret) and use nullifier_secret as a private input in the circuit while keeping nullifier as a public input. The zkSNARK proof would then also demonstrate that you know the pre-image for nullifier allowing you to withdraw from the contract. An attacker doesn’t gain anything from front-running your withdraw tx because even though he/she can create a leaf with the same nullifier, he/she will not be able to withdraw it without knowing the pre-image for nullifier.

The circuit for Miximus is currently:

```python
spend_hash = H(spend_preimage_var, nullifier_var)
leaf_hash = H(nullifier_var, spend_hash)
assert merkle_authenticate(path_var, address_bits, leaf_hash)
```

The leaf can be inserted by a third party without knowing the spend preimage. However they do know what the nullifier is so they can track if and when the leaf has been spent.

However, when publishing a proof the nullifier can be replayed, somebody can insert a new leaf with the same nullifier then withdraw it - denying the original leaf owner the opportunity to withdraw their own leaf.

The nullifier_var is specified by the withdrawer 

So, there are possibly 2 problems:

 1) When the depositor and withdrawer are different parties, the depositor knows when it has been withdrawn - this leaks information.
 2) The nullifier can be replayed by an observer

In an ideal world the following statements are true:

 * When the depositor and withdrawer are different parties, the depositor must not know when their deposit has been withdrawn
 * When a depositor makes the deposit, the owner of the spend key must be able to observe that the deposit which only then can withdraw has been made.
 * Any observer cannot be able to associate the deposit and withdraw by observing the nullifier and leaf hash
 * When a withdraw is made, no observer will be able to deny them, via front-running, the ability to withdraw their funds.

The preimage to the leaf is never revealed to the public - but the leaf is public knowledge an observed by everybody. The constituents of the leaf are known only by the two parties of the transaction.

Can we fix this? yondonfu suggests using a secret for the nullifier, which is known between only the two parties of the transaction, which fixes the second problem, for example:

```python
spend_hash = H(spend_preimage_var, nullifier_secret)
leaf_hash = H(nullifier_secret, spend_hash)
assert merkle_authenticate(path_var, address_bits, leaf_hash)
assert H(nullifier_secret) == nullifier_var
```

But, what about the first problem? Making it so that the depositor cannot know when their deposit has been withdrawn?

TODO: add pseudocode into miximus.hpp

**Comment by HarryR** [comment]
So, after some more review, it seems that the problem stems from allowing the nullifier to be arbitrarily chosen. This is a bad design and resulted in the problems described above. There is an easier way of fixing this problem without making the circuit even more complicated.

```python
def circuit(secret, path_var, address_bits, nullifier, root):
   leaf_hash = H(secret) # Prove we know the secret for the leaf
   assert root == merkle_authenticate(path_var, address_bits, leaf_hash) # Prove that leaf exists within the tree
   assert H(secret, address_bits) == nullifier # Prove that nullifier matches public input
```

As per the circuit above, this fixes the front-running problem while keeping all of the other properties.

If the same secret is used twice, only one withdraw will be possible. Adding `address_bits` to the nullifier hash will solve this problem, allowing the same leaf to be inserted multiple times, and each one will have a unique nullifier that prevents double-spends of the same leaf.

The nullifier cannot be chosen arbitrarily, even if the same leaf value is inserted twice (e.g. maliciously) it would only allow the recipient to withdraw twice as much.

The depositor is unable to link their deposit with a withdraw without knowing the secret preimage for the hash.

**Comment by barryWhiteHat** [comment]
Do you need to know the address of the tree where you want to deposit before you calculate your leaf?

This seems like a problem that will maek the deposit process complicated due to a race condition if two ppl depsoit to the same address.

**Comment by HarryR** [comment]
No, you don't need to know the address/index of the leaf in the tree when you deposit.

And, if you deposit two leaves with the same value, they will have different nullifiers.

Thirdly, if two people deposit using the same leaf, neither will known when their deposit has been withdrawn.

**Comment by barryWhiteHat** [comment]
Ah i see. You just hash the index with the nullifier. Let me think on that.

**Comment by HarryR** [comment]
There's a problem with this approach, that applies to both Pedersen Hash and MiMC, if you know the result of `H(secret)` and the leaf index you can calculate `H(secret, leaf_index)`
