### ISSUE TITLE
Document the Miximus / Semaphore construction

### ISSUE THREAD

**Issue by HarryR** [HarryR/ethsnarks-miximus#5]
We need to create a clear and concise specification for the Miximus / Semaphore circuit so it can externally and more formally validated.

 * LongsightF implementation
 * LongsightF parameters, parameter choices
 * Merkle tree construction using LongsightF, with shorter individual rounds but equivalent rounds given height of tree
 * Leaf hash semantics for both Miximus and Semaphore
 * Anonymity properties, breakdown of the guarantees and how they are achieved

Need to put this into a markdown file, with appropriate diagrams, so that it can be made into a PDF file for general distribution.

Need to reference relevant academic papers specifically for the safety of LongsightF in the tree construction. (TODO: dig these out from UOWHF research, Merkle-Damgård construct etc.)

## LongsightF implementation

TODO: circuit diagram for round function

Number of constraints

### Parameters

For the leaf:
 * `LongsightF-r322-e5`
 * Rounds: 322
 * Exponent: 5

For tree nodes:
  * `LongsightF-r12-e5`
  * Rounds: 12
  * Exponent: 5
  * Tree height: 29

## Tree construction

 Where `H_n()` is the LongsightF-r12-e5 function for nodes.
 Where `H_l()` is the LongsightF-r322-e5 function for leafs.

 * `leaf_i = H_l(A_i, H_l(B_i, C_i))`
 * `node_... = H_n(leaf_i, leaf_i+1)`
 * `node_... = H_n(node_..., node_...)`

## Leaf Hash Semantics

Miximus and Semaphore have different semantics, namely Semaphore requires an additional property which Miximus doesn't.

Each leaf requires the following properties:

 * One component of the hash, `T`, serves as a unique tag, this prevents double spends, double voting etc.
 * `leaf` is public, given `leaf` and knowledge of `A`, no participant other than the spender should be able to know that `T` is related to `A` or `leaf`.
 * Note: why is there a separate `A` when the hash could just be `H(C, T)` where `C` is a random Nonce?

The leaf construction is:

 * `B = H(C, T)`
 * `leaf = H(A, B)`

With Miximus each leaf can only be used once.

With Semaphore the leaf may be used multiple times, so the tag needs to be mixed with the `unique parameters` for that specific signal type.

**Comment by barryWhiteHat** [comment]
I agree in general, but think that we should abstract the hash function into a separate spec. 

My reasoning is that I am not convinced by the LongsightF construction. I need to take more time to study it. But I believe that sha256 is safest followed by pedersen commitments. Different applications will require different levels of security. So in general abstracting the hash function makes sense from the spec. 

Perhaps we should start a discussion about different hash functions and come to a consensus on what one to use?  Or guidelines about white to use under which circumstances, to get which security parameters?
